name: .NET Core Desktop

on:
  [ push , pull_request ]

jobs:
  Desktop-App-Runner:
    runs-on: self-hosted

    env:
      Solution_Name: GitHubActions\GitHubActions.sln

    steps:
      # - name: Dummy
      #   run:
      #     whoami
      
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x