name: .NET Core Desktop

on:
  [ push , pull_request ]

jobs:
  Build-Stage:
    runs-on: 
      - self-hosted
      - vs-test-work
    # env:
    #   Solution_Name: GitHubActions\GitHubActions.sln
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '3.1.x'
          
      - name: Build with .NET
        run: dotnet build --configuration Release
        working-directory: .\GitHubActions

  # Compile-Stage:
  #   runs-on: vs-test-work

  #   env:
  #     Solution_Name: GitHubActions\GitHubActions.sln

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0

  # Installer-Generation-SetUp-Deploy-Stage:
  #   runs-on: vs-test-work

  #   env:
  #     Solution_Name: GitHubActions\GitHubActions.sln

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0